# YAML document with parameters of the simulation
# Simulation parameters
Number of interaction: 1000000
Output directory: "./out/"
# Define the way we want to save the simulation:
# Among "Stack" (using OperationStack), "Last" (Only final state), "Freq" (TODO), "Off" (No save)
Save mode: "Stack"
Verbose: True # Default True

# Initial condition
# Among "Empty", "Random", "Groups" and "Reload"
# If "Groups" an additional parameter "Number of groups" must be added (default is 1)
# If "Reload" a "Reload directory" can be defined as well as a "Reload seed"
Init: "Empty"

# Model parameters
Community size: 220
Link minimum: 10
Cognitive capacity: 750
Heuristic: "RTH" # Among "SITH", "Complex", "RTH"
Temperature: 0.25

# Valid phenotypes (with caps): Trustful, Random, Optimistic, Pessimist, Envious
Strategy distributions:
  Envious: 0.3
  Optimist: 0.2
  Pessimist: 0.21
  Random: 0.12
  Trustful: 0.17
 