# YAML document with parameters of the simulation
# Simulation parameters
Number of interaction: 444675
Output directory: "./out/last/"
# Define the way we want to save the simulation:
# Among "Stack" (using OperationStack), "Last" (Only final state), "Freq" (TODO), "Off" (No save)
Save mode: "Last"
Verbose: True # Default True
# "Seed" must be a number
Seed: "distrib"

# Initial condition
# Among "Empty", "Random", "Groups"
# If "Groups" an additional parameter "Number of groups" must be added (default is 1)
Init: "Empty"

# Model parameters
Community size: 50
Link minimum:
  Mean: 10
  Sigma: 3
Cognitive capacity:
  Mean: 750
  Sigma: 100
Heuristic: "RTH" # Among "SITH", "Complex", "RTH"
Temperature: 0.25

# Valid phenotypes (with caps): Trustful, Random, Optimistic, Pessimist, Envious
Strategy distributions:
  Envious: 0.3
  Optimist: 0.2
  Pessimist: 0.21
  Random: 0.12
  Trustful: 0.17
 