# WAML document with parameters of the simulation
# Simulation parameters
Number of interaction: 100000
Output directory: "./out/empty_trust_optimist_C750_Th5/"

# Model parameters
Community size: 75
Link minimum: 5
Cognitive capacity: 750
Heuristic: "Trust" # Among "Simple", "Complex", "Trust"
Temperature: 0

# Valid phenotypes (with caps): Trustful, Random, Optimistic, Pessimist, Envious
Strategy distributions:
  Optimist: 1
 