# WAML document with parameters of the simulation
# Simulation parameters
Number of interaction: 200000
Output directory: "./out/empty_trust_total_C750_Th10/"

# Model parameters
Community size: 75
Link minimum: 10
Cognitive capacity: 750
Heuristic: "Trust" # Among "Simple", "Complex", "Trust"
Temperature: 0

# Valid phenotypes (with caps): Trustful, Random, Optimistic, Pessimist, Envious
Strategy distributions:
  Envious: 0.3
  Optimist: 0.2
  Pessimist: 0.21
  Random: 0.12
  Trustful: 0.17
 